name: Build iosApp
on:
  push:
    paths:
      - 'iosApp/**'
      - 'shared/**'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '*.gradle.kts'
      - '*.gradle'
      - '*.properties'
      - 'libs.versions.toml'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: false

      - name: Prep gradle
        run: chmod +x ./gradlew

      - name: Build iosApp
        run: |
          xcodebuild \
            -project iosApp/TechNexus.xcodeproj \
            -scheme TechNexus \
            -destination 'generic/platform=iOS Simulator' \
            -configuration Debug \
            PLATFORM_NAME=iphonesimulator \
            ARCHS=arm64 \
            EXPANDED_CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="-" \
            build
