name: Build iosApp
on:
  push:
    paths:
      - 'iosApp/**'
      - 'shared/**'
      - 'composeApp/**'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '*.gradle.kts'
      - 'gradle.properties'
      - '.github/workflows/build-ios.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: false

      - name: Prep gradle
        run: chmod +x ./gradlew

      - name: List Xcode versions
        run: ls /Applications/ | grep Xcode

      - name: Build iosApp
        run: |
          xcodebuild \
            -project iosApp/TechNexus.xcodeproj \
            -scheme TechNexus \
            -destination 'generic/platform=iOS Simulator' \
            -configuration Debug \
            PLATFORM_NAME=iphonesimulator \
            ARCHS=arm64 \
            CODE_SIGNING_ALLOWED=NO \
            build
