name: Build iosApp
on:
  push:
    paths:
      - 'iosApp/**'
      - 'shared/**'
      - 'composeApp/**'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '*.gradle.kts'
      - 'gradle.properties'
      - '.github/workflows/build-ios.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: false

      - name: Prep gradle
        run: chmod +x ./gradlew

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_26.3.app

      - name: Build iosApp
        run: |
          xcodebuild \
            -project iosApp/TechNexus.xcodeproj \
            -scheme TechNexus \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            build
